# Generated by Django 3.2.16 on 2022-11-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('deliverypoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('dateDeal', models.DateTimeField()),
                ('volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('deliveryStart', models.DateTimeField()),
                ('deliveryEnd', models.DateTimeField()),
                ('tool', models.CharField(max_length=255)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_counterparties', to='counterparties.counterparty')),
                ('deliveryPoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_deliveryPoints', to='deliverypoints.deliverypoint')),
            ],
            options={
                'unique_together': {('type', 'dateDeal', 'deliveryPoint', 'deliveryStart', 'deliveryEnd', 'tool', 'counterparty')},
            },
        ),
    ]
