# Generated by Django 3.2.16 on 2022-11-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together=set(),
        ),
    ]
