# Generated by Django 3.2.16 on 2022-11-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypoints', '0001_initial'),
        ('counterparties', '0001_initial'),
        ('deals', '0002_alter_deal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('type', 'dateDeal', 'deliveryPoint', 'deliveryStart', 'deliveryEnd', 'tool', 'counterparty')},
        ),
    ]
